@HotelListing.Api_HostAddress = https://localhost:7124

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
    "id": 4,
    "name": "Grand Plaza",
    "address": "123 Main St",
    "rating": 4.5
}

###

@id=4
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
    "id": 4,
    "name": "Test Hotel",
    "address": "123 Main St",
    "rating": 4.5
}

###
@id=2
GET {{HotelListing.Api_HostAddress}}/api/countries

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Test Country",
  "shortName": "TC"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "countryId": 2,
  "name": "Jamaica",
  "shortName": "JM"
}
###
